// <auto-generated />
using System;
using EventReservation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventReservation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817102254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EventReservation.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("booking_reference");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.BookingItem", b =>
                {
                    b.Property<int>("BookingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingItemId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("listing_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.HasKey("BookingItemId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ListingId");

                    b.ToTable("booking_items", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EventId"));

                    b.Property<DateTime?>("AnnounceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("announce_date");

                    b.Property<DateTime?>("CreatedAtSource")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_source");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("DateTbd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("date_tbd");

                    b.Property<DateTime>("DatetimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datetime_utc");

                    b.Property<DateTime?>("EndDatetimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_datetime_utc");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsGa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_ga");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_open");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("schedule_status");

                    b.Property<bool>("SeatSelectionEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("seat_selection_enabled");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext")
                        .HasColumnName("short_name");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TaxonomyName")
                        .HasColumnType("longtext")
                        .HasColumnName("taxonomy_name");

                    b.Property<string>("TaxonomySubName")
                        .HasColumnType("longtext")
                        .HasColumnName("taxonomy_sub_name");

                    b.Property<bool>("TimeTbd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("time_tbd");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.EventPerformer", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int")
                        .HasColumnName("performer_id");

                    b.HasKey("EventId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.ToTable("event_performers", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Listing", b =>
                {
                    b.Property<string>("ListingId")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("listing_id");

                    b.Property<int?>("DealBucket")
                        .HasColumnType("int")
                        .HasColumnName("deal_bucket");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("longtext")
                        .HasColumnName("delivery_type");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("InHandDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("in_hand_date");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("listing_status");

                    b.Property<string>("Marketplace")
                        .HasColumnType("longtext")
                        .HasColumnName("marketplace");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("int")
                        .HasColumnName("quantity_remaining");

                    b.Property<string>("RowLabel")
                        .HasColumnType("longtext")
                        .HasColumnName("row_label");

                    b.Property<string>("Section")
                        .HasColumnType("longtext")
                        .HasColumnName("section");

                    b.Property<string>("SectionFull")
                        .HasColumnType("longtext")
                        .HasColumnName("section_full");

                    b.Property<string>("SplitType")
                        .HasColumnType("longtext")
                        .HasColumnName("split_type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unit_price");

                    b.HasKey("ListingId");

                    b.HasIndex("EventId");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Performer", b =>
                {
                    b.Property<int>("PerformerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("performer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PerformerId"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DivisionName")
                        .HasColumnType("longtext")
                        .HasColumnName("division_name");

                    b.Property<string>("DivisionShortName")
                        .HasColumnType("longtext")
                        .HasColumnName("division_short_name");

                    b.Property<int?>("HomeVenueId")
                        .HasColumnType("int")
                        .HasColumnName("home_venue_id");

                    b.Property<bool>("IsEvent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_event");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("Popularity")
                        .HasColumnType("int")
                        .HasColumnName("popularity");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("score");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext")
                        .HasColumnName("short_name");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext")
                        .HasColumnName("slug");

                    b.Property<string>("TaxonomyName")
                        .HasColumnType("longtext")
                        .HasColumnName("taxonomy_name");

                    b.Property<string>("TaxonomySubName")
                        .HasColumnType("longtext")
                        .HasColumnName("taxonomy_sub_name");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("PerformerId");

                    b.HasIndex("HomeVenueId");

                    b.ToTable("performers", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("theme_preference");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("AddressCity")
                        .HasColumnType("longtext")
                        .HasColumnName("address_city");

                    b.Property<string>("AddressCountry")
                        .HasColumnType("longtext")
                        .HasColumnName("address_country");

                    b.Property<string>("AddressPostalCode")
                        .HasColumnType("longtext")
                        .HasColumnName("address_postal_code");

                    b.Property<string>("AddressState")
                        .HasColumnType("longtext")
                        .HasColumnName("address_state");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("longtext")
                        .HasColumnName("address_street");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<int?>("MetroCode")
                        .HasColumnType("int")
                        .HasColumnName("metro_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("PopularityCount")
                        .HasColumnType("int")
                        .HasColumnName("popularity_count");

                    b.Property<decimal?>("PopularityScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("popularity_score");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext")
                        .HasColumnName("slug");

                    b.Property<string>("Timezone")
                        .HasColumnType("longtext")
                        .HasColumnName("timezone");

                    b.HasKey("VenueId");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Booking", b =>
                {
                    b.HasOne("EventReservation.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventReservation.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.BookingItem", b =>
                {
                    b.HasOne("EventReservation.Domain.Entities.Booking", "Booking")
                        .WithMany("Items")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventReservation.Domain.Entities.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Event", b =>
                {
                    b.HasOne("EventReservation.Domain.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.EventPerformer", b =>
                {
                    b.HasOne("EventReservation.Domain.Entities.Event", "Event")
                        .WithMany("EventPerformers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventReservation.Domain.Entities.Performer", "Performer")
                        .WithMany("EventPerformers")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Listing", b =>
                {
                    b.HasOne("EventReservation.Domain.Entities.Event", "Event")
                        .WithMany("Listings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Performer", b =>
                {
                    b.HasOne("EventReservation.Domain.Entities.Venue", "HomeVenue")
                        .WithMany("Performers")
                        .HasForeignKey("HomeVenueId");

                    b.Navigation("HomeVenue");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventPerformers");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Performer", b =>
                {
                    b.Navigation("EventPerformers");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventReservation.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Performers");
                });
#pragma warning restore 612, 618
        }
    }
}
